// Generated by gencpp from file path_publisher/Floats.msg
// DO NOT EDIT!


#ifndef PATH_PUBLISHER_MESSAGE_FLOATS_H
#define PATH_PUBLISHER_MESSAGE_FLOATS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_publisher
{
template <class ContainerAllocator>
struct Floats_
{
  typedef Floats_<ContainerAllocator> Type;

  Floats_()
    : index(0)
    , length(0)
    , data()  {
    }
  Floats_(const ContainerAllocator& _alloc)
    : index(0)
    , length(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _length_type;
  _length_type length;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::path_publisher::Floats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_publisher::Floats_<ContainerAllocator> const> ConstPtr;

}; // struct Floats_

typedef ::path_publisher::Floats_<std::allocator<void> > Floats;

typedef boost::shared_ptr< ::path_publisher::Floats > FloatsPtr;
typedef boost::shared_ptr< ::path_publisher::Floats const> FloatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_publisher::Floats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_publisher::Floats_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_publisher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'path_publisher': ['/home/local/GACL/gharms/catkin_ws_ur/src/path_publisher/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_publisher::Floats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_publisher::Floats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_publisher::Floats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_publisher::Floats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_publisher::Floats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_publisher::Floats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_publisher::Floats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3399fec90a07c2467f8a8e04ebc2b5a5";
  }

  static const char* value(const ::path_publisher::Floats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3399fec90a07c246ULL;
  static const uint64_t static_value2 = 0x7f8a8e04ebc2b5a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_publisher::Floats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_publisher/Floats";
  }

  static const char* value(const ::path_publisher::Floats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_publisher::Floats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n\
int32 length\n\
float32[] data\n\
";
  }

  static const char* value(const ::path_publisher::Floats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_publisher::Floats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.length);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Floats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_publisher::Floats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_publisher::Floats_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PUBLISHER_MESSAGE_FLOATS_H
